name: Unit Tests

on:
  # Should only be used by other workflows
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
jobs:
  unit_tests:
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - go-version: 1.19.x
            os: ubuntu-latest
          - go-version: 1.20.x
            os: ubuntu-latest
          - go-version: 1.21.x
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Make all
        run: make all

      - name: Make Test
        id: unit-test
        run: make test

  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Make all
        run: make all

      - name: Make Coverage
        run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
